name: google_maps_useful_stuff
description: Google maps useful stuff

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  location_permissions: ^2.0.5
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.3.0
  google_maps_cluster_manager: ^0.1.0
  google_maps_place_picker: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/markers/